# Generated by Django 4.1.1 on 2022-11-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], default='', max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
    ]
