# Generated by Django 4.1.1 on 2022-11-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmgmt', '0002_alter_client_category_alter_client_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], default='', max_length=50, null=True, verbose_name='Category:'),
        ),
    ]
