# Generated by Django 4.1.1 on 2022-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0004_invoice_invoice_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created:'),
        ),
    ]
