# Generated by Django 4.1.1 on 2022-11-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0007_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
