# Generated by Django 4.1.1 on 2022-11-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0008_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Client Name:'),
        ),
    ]
