# Generated by Django 4.1.1 on 2022-11-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('PC Component', 'PC Component'), ('IT Equipment', 'IT Equipment')], default='', max_length=50, null=True, verbose_name='Category:'),
        ),
    ]
