# Generated by Django 4.1.1 on 2022-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0002_alter_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='set_price',
            field=models.CharField(blank=True, choices=[('PHP 500', 'PHP 500'), ('PHP 1000', 'PHP 1000')], default='', max_length=50, null=True, verbose_name='Pricing:'),
        ),
    ]
