# Generated by Django 4.1.1 on 2022-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0006_alter_stock_category_alter_stock_set_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, choices=[('Chocolate Donut', 'Chocolate Donut'), ('Strawberry Donut', 'Strawberry Donut'), ('Blueberry Donut', 'Blueberry Donut'), ('Vanilla Donut', 'Vanilla Donut')], max_length=50, null=True, verbose_name='Item Name:'),
        ),
    ]
