# Generated by Django 4.1.1 on 2022-11-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0007_alter_stock_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name:'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='set_price',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Pricing:'),
        ),
    ]
