# Generated by Django 4.1.1 on 2022-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0008_alter_stock_item_name_alter_stock_set_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Category:'),
        ),
    ]
