# Generated by Django 4.1.1 on 2022-11-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invmgmt', '0010_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Category:'),
        ),
    ]
